### PR TITLE
Add pointerEvents. Fixes #2

### LINKED ISSUE #2: Disable pointer events while editable
Simpla admin should kill pointer events on all non-Simpla elements while in edit mode. This makes editing with Simpla more robust and less frustration-prone. Then to click on a link, the user can just quickly toggle edit mode off then back on.

We did have a tree-walker around for this, but it's long gone. Will need input from @bedeoverend on best implementation. Business logic would be to disable pointer events on all elements that don't match the following regex:

```js
/^simpla-/.test(el.tagName)
```

This should also be configurable once #1 is implemented

### PR DESCRIPTION
**Pull request by bedeoverend**
This adds in a `pointerEvents` property which allows users to configure admin to disable pointer-events / clicks on all non-simpla elements. This means that while editing, a user can safely click on a link or similar that wraps up a Simpla element / sits on top of a Simpla element.

Tasks: 
- [x] Stop events from bubbling out of simpla-* elements
- [x] Disable all pointer events on non-simpla elements

Both need to be done as there are two common scenarios: 

1. A simpla element is _wrapped_ in an element which listens for clicks / `a` tag
2. A simpla element has an element visually appear above to intercept click events e.g. on hover click an image to expand

The first can be fixed by blocking bubbling click events out of the simpla element, and also calling `preventDefault` on the event - to stop anchors from activating.

The second can be fixed by disabling pointer events on the `body`, but re-enabling them on any simpla element. A concern here is needing regular pointer events to work to perhaps see an image e.g. hover to show image that needs editing - though I would assume this is the larger edge case.

Fixes #2

### CODE REVIEW

**Comment by bedeoverend** [comment]
@seaneking this is ready for review, could you take a look? Something that's annoying though is there's no visual distinction between what's interactive now. 

We could re-implement the old tree walker which goes through and changes the opacity to make everything not-simpla fade out, but thats pretty nasty - e.g. I was working on a site with hover overlays that had opacity 0 normally; their opacity got clobbered so they were semi-opaque, looked super broken, getting around that would be a perf nightmare too as it would mean using `getComputedStyle` on every element on the page...not viable

**Comment by bedeoverend** [comment]
Oh also I named it `stayInteractive`:

```js
window.SimplaAdmin = {
  stayInteractive: true // To stay interactive while editable
}
```

but happy to change to whatever.

**Comment by madeleineostoja** [comment]
- Dist not minified
- It's fine that there's no visual distinction, this just protects unwanted clicks, doesn't matter what's editable and not
- Yeah I might tweak the name, `stayInteractive` is pretty confusing IMO

**Comment by madeleineostoja** [comment]
What about `protectEditing` for the option name? Don't like `stayInteractive` because you're passing `true` to disable a feature.

I'd say either that or something along the lines of `disableClicks`, `stopInteraction`, etc. Anyway, have written docs for the feature and ready to merge, just finalise the opt name and then I'll push up, merge, and make a new minor version.

**Comment by bedeoverend** [comment]
Dist is minified yeah? Latest commit on this branch? And yeah fair enough re: visuals - separate concern. 

I'm happy with `protectEditing` if you are.

**Comment by bedeoverend** [comment]
Also - if we push it with it turned on by default, is that considered a minor or a major change?

**Comment by madeleineostoja** [comment]
Close enough to minor, considering this element isn't all that 'released' yet, and it's not technically breaking for simpla-admin

**Pull request merged**
